export const passportConstants = {
    GET_REQUEST: 'PASSPORTS_GET_REQUEST',
    GET_SUCCESS: 'PASSPORTS_GET_SUCCESS',
    GET_FAILURE: 'PASSPORTS_GET_FAILURE',

    GETALL_REQUEST: 'PASSPORTS_GETALL_REQUEST',
    GETALL_SUCCESS: 'PASSPORTS_GETALL_SUCCESS',
    GETALL_FAILURE: 'PASSPORTS_GETALL_FAILURE',

    PUBLIC_CREATE_REQUEST: 'PASSPORTS_PUBLIC_CREATE_REQUEST',
    PUBLIC_CREATE_SUCCESS: 'PASSPORTS_PUBLIC_CREATE_SUCCESS',
    PUBLIC_CREATE_FAILURE: 'PASSPORTS_PUBLIC_CREATE_FAILURE',

    CREATE_REQUEST: 'PASSPORTS_CREATE_REQUEST',
    CREATE_SUCCESS: 'PASSPORTS_CREATE_SUCCESS',
    CREATE_FAILURE: 'PASSPORTS_CREATE_FAILURE',

    UPDATE_REQUEST: 'PASSPORTS_UPDATE_REQUEST',
    UPDATE_SUCCESS: 'PASSPORTS_UPDATE_SUCCESS',
    UPDATE_FAILURE: 'PASSPORTS_UPDATE_FAILURE',

    DELETE_REQUEST: 'PASSPORTS_DELETE_REQUEST',
    DELETE_SUCCESS: 'PASSPORTS_DELETE_SUCCESS',
    DELETE_FAILURE: 'PASSPORTS_DELETE_FAILURE'    
};

export const authenticationConstants = {
    LOGIN_REQUEST: 'AUTH_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'AUTH_LOGIN_FAILURE',

    LOGOUT: 'AUTH_LOGOUT',
    
    GET_REQUEST: 'GET_AUTH_REQUEST',
    GET_SUCCESS: 'GET_AUTH_SUCCESS',
    GET_FAILURE: 'GET_AUTH_FAILURE',
};